Bibliotekos

In [1]:
import pandas as pd

Duomenų įsikėlimas

In [2]:
meteo_data = pd.read_csv("Matavimas.csv", sep = ',')
meteo_data.head(5)

C:\Users\eveli\AppData\Local\Temp\ipykernel_5896\2527246135.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  meteo_data = pd.read_csv("Matavimas.csv", sep = ',')

,_type,_id,_revision,_page.next,vda_prime_key,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
0,datasets/gov/lhmt/stebejimai/Matavimas,1eff61d5-399f-4348-a676-1d0645f3cef1,082b0352-2ea8-467b-aea3-b3ba24fbc0d1,NaN,000001825dce7a2,Varėnos AMS,varenos-ams,24.551760,54.248271,2024-12-19T11:00:00,8.8,7.3,2.6,6.8,189.0,88.0,999.7,88.0,0.0,debesuota
1,datasets/gov/lhmt/stebejimai/Matavimas,6a1ade5a-7864-4c80-a012-6e5046e9353e,77a2819b-c0fa-4706-b543-62332bd5ed57,NaN,000002c87b99a6c,Utenos AMS,utenos-ams,25.589692,55.515321,2015-04-01T16:00:00,5.2,5.2,2.1,4.1,254.0,88.0,987.2,91.0,0.0,debesuota
2,datasets/gov/lhmt/stebejimai/Matavimas,584feb71-3f2b-4440-b2ca-64b9a8fd0a3f,f4453408-51c7-4d7a-b7b6-4af9f0b82b2d,NaN,00001d8a886c858,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2020-09-24T14:00:00,22.8,22.8,4.3,8.2,173.0,13.0,1008.9,49.0,0.0,mažai debesuota
3,datasets/gov/lhmt/stebejimai/Matavimas,3f8bbe2a-221d-49bf-8fbd-e91b2b25f51e,a1aa4732-0e09-4771-8e9f-4cf65e515fc3,NaN,00001e35fc20c59,Raseinių AMS,raseiniu-ams,23.133073,55.394569,2017-01-24T13:00:00,1.6,-1.9,3.4,5.8,291.0,88.0,1019.9,86.0,0.0,debesuota
4,datasets/gov/lhmt/stebejimai/Matavimas,f8788082-8986-4fa6-8b0d-577ac9dd795d,762c60b8-9ee2-498f-810e-8407a834e905,NaN,00001e87f6d2501,Dūkšto AMS,duksto-ams,26.316140,55.517856,2016-11-11T18:00:00,-3.1,-3.1,0.9,3.1,261.0,100.0,1019.4,92.0,0.0,trumpas sniegas

In [3]:
meteo_data_clean = meteo_data.drop(columns = ['_type', '_id', '_revision', '_page.next', 'vda_prime_key'])
meteo_data_clean['stebejimo_laikas'] = pd.to_datetime(meteo_data_clean['stebejimo_laikas'])
meteo_data_clean['metai'] = meteo_data_clean['stebejimo_laikas'].dt.year
meteo_data_clean.head(5)

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos,metai
0,Varėnos AMS,varenos-ams,24.551760,54.248271,2024-12-19 11:00:00,8.8,7.3,2.6,6.8,189.0,88.0,999.7,88.0,0.0,debesuota,2024
1,Utenos AMS,utenos-ams,25.589692,55.515321,2015-04-01 16:00:00,5.2,5.2,2.1,4.1,254.0,88.0,987.2,91.0,0.0,debesuota,2015
2,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2020-09-24 14:00:00,22.8,22.8,4.3,8.2,173.0,13.0,1008.9,49.0,0.0,mažai debesuota,2020
3,Raseinių AMS,raseiniu-ams,23.133073,55.394569,2017-01-24 13:00:00,1.6,-1.9,3.4,5.8,291.0,88.0,1019.9,86.0,0.0,debesuota,2017
4,Dūkšto AMS,duksto-ams,26.316140,55.517856,2016-11-11 18:00:00,-3.1,-3.1,0.9,3.1,261.0,100.0,1019.4,92.0,0.0,trumpas sniegas,2016

In [4]:
meteo_data_clean.shape

(2463879, 16)

Stočių pavadinimai

In [5]:
station_names = meteo_data_clean["stoties_pavadinimas"].unique()
station_names

array(['Varėnos AMS', 'Utenos AMS', 'Vilniaus AMS', 'Raseinių AMS',
       'Dūkšto AMS', 'Šiaulių AMS', 'Druskininkų AMS', 'Mažeikių AMS',
       'Plungės AMS', 'Rokiškio AMS', 'Vėžaičių AMS', 'Kybartų AMS',
       'Kalvarijos AMS', 'Pagėgių AMS', 'Lazdijų AMS', 'Joniškio AMS',
       'Ukmergės AMS', 'Biržų AMS', 'Laukuvos AMS', 'Klaipėdos AMS',
       'Nidos AMS', 'Kauno AMS', 'Šilutės AMS', 'Zarasų AMS',
       'Rietavo AMS', 'Telšių AMS', 'Marijampolės AMS', 'Pakruojo AMS',
       'Panevėžio AMS', 'Kelmės AMS', 'Šakių AMS', 'Dotnuvos AMS',
       'Skuodo AMS', 'Jonavos AMS', 'Alytaus AMS', 'Akmenės AMS',
       'Tauragės AMS', 'Šeduvos AMS', 'Kretingos AMS', 'Molėtų AMS',
       'Elektrėnų AMS', 'Trakų AMS', 'Šalčininkų AMS', 'Anykščių AMS',
       'Kupiškio AMS', 'Birštono AMS', 'Prienų AMS', 'Kaišiadorių AMS',
       'Jurbarko AMS', 'Kazlų Rūdos AMS', 'Ventės AMS', 'Švenčionių AMS'],
      dtype=object)

Pirmos 10 stočių pagal duomenų skaičių

In [6]:
data_count_station = []
for station in station_names:
    data_count_station.append(len(meteo_data_clean[meteo_data_clean['stoties_pavadinimas'] == f'{station}']))
data_count_station_df = pd.DataFrame(data_count_station, index = station_names, columns=['skaicius'])
data_count_station_df.sort_values(by = 'skaicius', ascending = False)[:10]

              skaicius
Utenos AMS      112145
Dūkšto AMS      112143
Varėnos AMS     112142
Kybartų AMS     112136
Ukmergės AMS    112134
Šilutės AMS     112133
Kauno AMS       112132
Raseinių AMS    112131
Vilniaus AMS    112129
Biržų AMS       112124

Praleistos reikšmės visame rinkinyje

In [7]:
column_nan_count = meteo_data_clean.isnull().sum()
column_nan_count

stoties_pavadinimas         0
stoties_kodas               0
ilguma                      0
platuma                     0
stebejimo_laikas            0
oro_temp                  213
juntamoji_temp         356614
vejo_greitis           355728
vejo_gusis             355794
vejo_kryptis           357104
debesuotumas           502441
slegis_juros_lyg       381345
santyk_oro_dregme        7294
kritutliu_kiekis         2144
oro_salygos            470413
metai                       0
dtype: int64

#### Vilniaus stotis analizė

In [8]:
data_Vilnius = meteo_data_clean[meteo_data_clean['stoties_pavadinimas'] == 'Vilniaus AMS']
data_Vilnius.shape

(112129, 16)

Praleistos reikšmės pagal stulpelį

In [9]:
data_Vilnius.isnull().sum()

stoties_pavadinimas       0
stoties_kodas             0
ilguma                    0
platuma                   0
stebejimo_laikas          0
oro_temp                 30
juntamoji_temp           34
vejo_greitis             37
vejo_gusis               44
vejo_kryptis             74
debesuotumas           2226
slegis_juros_lyg         30
santyk_oro_dregme        40
kritutliu_kiekis         38
oro_salygos             419
metai                     0
dtype: int64

Min ir max laikas:

In [12]:
print(min(data_Vilnius["stebejimo_laikas"]))
print(max(data_Vilnius["stebejimo_laikas"]))

2013-04-10 00:00:00
2026-03-11 23:00:00

Praleistos reikšmės pagal metus kiekvienam stulpeliui

In [10]:
station_year = data_Vilnius["metai"].unique()
station_year.sort()
print(station_year)

[2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026]

In [13]:
nan_year_result = []
for year in station_year:
    nan_year_result.append(data_Vilnius[data_Vilnius['metai'] == year].isnull().sum())
nan_year_Vilnius = pd.DataFrame(nan_year_result, index = station_year)
nan_year_Vilnius

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos,metai
2013,0,0,0,0,0,2,2,1,1,1,101,0,2,0,1,0
2014,0,0,0,0,0,0,0,0,0,40,187,0,0,4,32,0
2015,0,0,0,0,0,0,0,0,0,0,202,0,2,0,36,0
2016,0,0,0,0,0,1,1,1,1,1,138,0,1,1,1,0
2017,0,0,0,0,0,0,0,0,0,0,112,0,0,0,21,0
2018,0,0,0,0,0,0,0,2,3,0,173,1,0,1,19,0
2019,0,0,0,0,0,0,0,1,0,0,130,0,0,6,1,0
2020,0,0,0,0,0,16,16,18,15,18,306,16,17,0,151,0
2021,0,0,0,0,0,0,0,0,0,0,149,0,0,0,35,0
2022,0,0,0,0,0,0,0,0,0,0,270,0,0,0,99,0
2023,0,0,0,0,0,0,0,0,0,0,111,0,3,0,0,0
2024,0,0,0,0,0,0,0,1,3,1,103,0,0,14,5,0
2025,0,0,0,0,0,11,15,13,21,13,216,13,15,12,17,0
2026,0,0,0,0,0,0,0,0,0,0,28,0,0,0,1,0