Bibliotekos

In [1]:
import pandas as pd
import datetime

Duomenų įsikėlimas

In [2]:
meteo_data = pd.read_csv("Matavimas.csv", sep = ',')
meteo_data.head(5)

C:\Users\eveli\AppData\Local\Temp\ipykernel_31812\2527246135.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  meteo_data = pd.read_csv("Matavimas.csv", sep = ',')

,_type,_id,_revision,_page.next,vda_prime_key,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
0,datasets/gov/lhmt/stebejimai/Matavimas,1eff61d5-399f-4348-a676-1d0645f3cef1,082b0352-2ea8-467b-aea3-b3ba24fbc0d1,NaN,000001825dce7a2,Varėnos AMS,varenos-ams,24.551760,54.248271,2024-12-19T11:00:00,8.8,7.3,2.6,6.8,189.0,88.0,999.7,88.0,0.0,debesuota
1,datasets/gov/lhmt/stebejimai/Matavimas,6a1ade5a-7864-4c80-a012-6e5046e9353e,77a2819b-c0fa-4706-b543-62332bd5ed57,NaN,000002c87b99a6c,Utenos AMS,utenos-ams,25.589692,55.515321,2015-04-01T16:00:00,5.2,5.2,2.1,4.1,254.0,88.0,987.2,91.0,0.0,debesuota
2,datasets/gov/lhmt/stebejimai/Matavimas,584feb71-3f2b-4440-b2ca-64b9a8fd0a3f,f4453408-51c7-4d7a-b7b6-4af9f0b82b2d,NaN,00001d8a886c858,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2020-09-24T14:00:00,22.8,22.8,4.3,8.2,173.0,13.0,1008.9,49.0,0.0,mažai debesuota
3,datasets/gov/lhmt/stebejimai/Matavimas,3f8bbe2a-221d-49bf-8fbd-e91b2b25f51e,a1aa4732-0e09-4771-8e9f-4cf65e515fc3,NaN,00001e35fc20c59,Raseinių AMS,raseiniu-ams,23.133073,55.394569,2017-01-24T13:00:00,1.6,-1.9,3.4,5.8,291.0,88.0,1019.9,86.0,0.0,debesuota
4,datasets/gov/lhmt/stebejimai/Matavimas,f8788082-8986-4fa6-8b0d-577ac9dd795d,762c60b8-9ee2-498f-810e-8407a834e905,NaN,00001e87f6d2501,Dūkšto AMS,duksto-ams,26.316140,55.517856,2016-11-11T18:00:00,-3.1,-3.1,0.9,3.1,261.0,100.0,1019.4,92.0,0.0,trumpas sniegas

In [3]:
meteo_data_clean = meteo_data.drop(columns = ['_type', '_id', '_revision', '_page.next', 'vda_prime_key'])
meteo_data_clean['stebejimo_laikas'] = pd.to_datetime(meteo_data_clean['stebejimo_laikas'])
meteo_data_clean.head(5)

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
0,Varėnos AMS,varenos-ams,24.551760,54.248271,2024-12-19 11:00:00,8.8,7.3,2.6,6.8,189.0,88.0,999.7,88.0,0.0,debesuota
1,Utenos AMS,utenos-ams,25.589692,55.515321,2015-04-01 16:00:00,5.2,5.2,2.1,4.1,254.0,88.0,987.2,91.0,0.0,debesuota
2,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2020-09-24 14:00:00,22.8,22.8,4.3,8.2,173.0,13.0,1008.9,49.0,0.0,mažai debesuota
3,Raseinių AMS,raseiniu-ams,23.133073,55.394569,2017-01-24 13:00:00,1.6,-1.9,3.4,5.8,291.0,88.0,1019.9,86.0,0.0,debesuota
4,Dūkšto AMS,duksto-ams,26.316140,55.517856,2016-11-11 18:00:00,-3.1,-3.1,0.9,3.1,261.0,100.0,1019.4,92.0,0.0,trumpas sniegas

In [4]:
meteo_data_clean.shape

(2463879, 15)

Stočių pavadinimai

In [5]:
station_names = meteo_data_clean["stoties_pavadinimas"].unique()
station_names

array(['Varėnos AMS', 'Utenos AMS', 'Vilniaus AMS', 'Raseinių AMS',
       'Dūkšto AMS', 'Šiaulių AMS', 'Druskininkų AMS', 'Mažeikių AMS',
       'Plungės AMS', 'Rokiškio AMS', 'Vėžaičių AMS', 'Kybartų AMS',
       'Kalvarijos AMS', 'Pagėgių AMS', 'Lazdijų AMS', 'Joniškio AMS',
       'Ukmergės AMS', 'Biržų AMS', 'Laukuvos AMS', 'Klaipėdos AMS',
       'Nidos AMS', 'Kauno AMS', 'Šilutės AMS', 'Zarasų AMS',
       'Rietavo AMS', 'Telšių AMS', 'Marijampolės AMS', 'Pakruojo AMS',
       'Panevėžio AMS', 'Kelmės AMS', 'Šakių AMS', 'Dotnuvos AMS',
       'Skuodo AMS', 'Jonavos AMS', 'Alytaus AMS', 'Akmenės AMS',
       'Tauragės AMS', 'Šeduvos AMS', 'Kretingos AMS', 'Molėtų AMS',
       'Elektrėnų AMS', 'Trakų AMS', 'Šalčininkų AMS', 'Anykščių AMS',
       'Kupiškio AMS', 'Birštono AMS', 'Prienų AMS', 'Kaišiadorių AMS',
       'Jurbarko AMS', 'Kazlų Rūdos AMS', 'Ventės AMS', 'Švenčionių AMS'],
      dtype=object)

Pirmos 10 stočių pagal stebėjimų skaičių

In [6]:
data_count_station = []
for station in station_names:
    data_count_station.append(len(meteo_data_clean[meteo_data_clean['stoties_pavadinimas'] == f'{station}']))
data_count_station_df = pd.DataFrame(data_count_station, index = station_names, columns=['skaicius'])
data_count_station_df.sort_values(by = 'skaicius', ascending = False)[:10]

              skaicius
Utenos AMS      112145
Dūkšto AMS      112143
Varėnos AMS     112142
Kybartų AMS     112136
Ukmergės AMS    112134
Šilutės AMS     112133
Kauno AMS       112132
Raseinių AMS    112131
Vilniaus AMS    112129
Biržų AMS       112124

Praleistos reikšmės visame rinkinyje

In [7]:
column_nan_count = meteo_data_clean.isnull().sum()
column_nan_count

stoties_pavadinimas         0
stoties_kodas               0
ilguma                      0
platuma                     0
stebejimo_laikas            0
oro_temp                  213
juntamoji_temp         356614
vejo_greitis           355728
vejo_gusis             355794
vejo_kryptis           357104
debesuotumas           502441
slegis_juros_lyg       381345
santyk_oro_dregme        7294
kritutliu_kiekis         2144
oro_salygos            470413
dtype: int64

Pirmos 10 stočių pagal mažiausią praleistų reikšmių skaičių

In [8]:
na_by_station = meteo_data_clean.groupby('stoties_pavadinimas').apply(lambda x: x.isnull().sum().sum())
na_by_station.sort_values(ascending = True)[:10]

stoties_pavadinimas
Utenos AMS       1405
Kybartų AMS      2058
Klaipėdos AMS    2151
Varėnos AMS      2891
Vilniaus AMS     2972
Šilutės AMS      3193
Kauno AMS        3197
Panevėžio AMS    3674
Nidos AMS        3862
Telšių AMS       4363
dtype: int64

#### Vilniaus stotis analizė

In [9]:
data_Vilnius = meteo_data_clean[meteo_data_clean['stoties_pavadinimas'] == 'Vilniaus AMS']
data_Vilnius.shape

(112129, 15)

Praleistos reikšmės pagal stulpelį

In [10]:
data_Vilnius.isnull().sum()

stoties_pavadinimas       0
stoties_kodas             0
ilguma                    0
platuma                   0
stebejimo_laikas          0
oro_temp                 30
juntamoji_temp           34
vejo_greitis             37
vejo_gusis               44
vejo_kryptis             74
debesuotumas           2226
slegis_juros_lyg         30
santyk_oro_dregme        40
kritutliu_kiekis         38
oro_salygos             419
dtype: int64

Min ir max laikas:

In [11]:
print(min(data_Vilnius["stebejimo_laikas"]))
print(max(data_Vilnius["stebejimo_laikas"]))

2013-04-10 00:00:00
2026-03-11 23:00:00

Praleistos reikšmės pagal metus kiekvienam stulpeliui

In [12]:
station_year = data_Vilnius["stebejimo_laikas"].dt.year.unique()
station_year.sort()
nan_year_result = []
for year in station_year:
    nan_year_result.append(data_Vilnius[data_Vilnius["stebejimo_laikas"].dt.year == year].isnull().sum())
nan_year_Vilnius = pd.DataFrame(nan_year_result, index = station_year)
nan_year_Vilnius

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
2013,0,0,0,0,0,2,2,1,1,1,101,0,2,0,1
2014,0,0,0,0,0,0,0,0,0,40,187,0,0,4,32
2015,0,0,0,0,0,0,0,0,0,0,202,0,2,0,36
2016,0,0,0,0,0,1,1,1,1,1,138,0,1,1,1
2017,0,0,0,0,0,0,0,0,0,0,112,0,0,0,21
2018,0,0,0,0,0,0,0,2,3,0,173,1,0,1,19
2019,0,0,0,0,0,0,0,1,0,0,130,0,0,6,1
2020,0,0,0,0,0,16,16,18,15,18,306,16,17,0,151
2021,0,0,0,0,0,0,0,0,0,0,149,0,0,0,35
2022,0,0,0,0,0,0,0,0,0,0,270,0,0,0,99
2023,0,0,0,0,0,0,0,0,0,0,111,0,3,0,0
2024,0,0,0,0,0,0,0,1,3,1,103,0,0,14,5
2025,0,0,0,0,0,11,15,13,21,13,216,13,15,12,17
2026,0,0,0,0,0,0,0,0,0,0,28,0,0,0,1

#### Galutinės aibės paruošimas

In [18]:
meteo_Vilnius = data_Vilnius[(data_Vilnius["stebejimo_laikas"].dt.date >= datetime.date(2017,11,1)) & (data_Vilnius["stebejimo_laikas"].dt.date <= datetime.date(2026,3,1))].sort_values(by='stebejimo_laikas')
meteo_Vilnius.shape

(71909, 15)

In [15]:
meteo_Vilnius.head(5)

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
1577877,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2017-11-01 00:00:00,0.7,-2.5,2.8,4.9,312.0,88.0,1012.1,90.0,0.0,debesuota
854505,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2017-11-01 01:00:00,0.4,0.4,0.8,2.5,309.0,88.0,1012.4,91.0,0.0,debesuota
965038,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2017-11-01 02:00:00,0.8,0.8,1.0,2.7,247.0,100.0,1012.4,91.0,0.0,debesuota
2111098,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2017-11-01 03:00:00,0.7,0.7,1.3,2.9,259.0,88.0,1012.3,92.0,0.0,debesuota
129024,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2017-11-01 04:00:00,0.5,-2.4,2.5,3.9,238.0,88.0,1011.9,93.0,0.0,debesuota

In [16]:
meteo_Vilnius.tail(5)

,stoties_pavadinimas,stoties_kodas,ilguma,platuma,stebejimo_laikas,oro_temp,juntamoji_temp,vejo_greitis,vejo_gusis,vejo_kryptis,debesuotumas,slegis_juros_lyg,santyk_oro_dregme,kritutliu_kiekis,oro_salygos
1900595,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2026-03-01 19:00:00,1.8,-2.5,4.7,9.1,285.0,100.0,1021.9,83.0,0.0,debesuota
2371248,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2026-03-01 20:00:00,1.8,-2.6,4.9,9.3,275.0,100.0,1022.0,78.0,0.0,debesuota
2248742,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2026-03-01 21:00:00,1.8,-1.8,3.6,8.7,284.0,100.0,1022.1,77.0,0.0,debesuota
1077900,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2026-03-01 22:00:00,1.7,-1.4,2.9,7.6,266.0,100.0,1022.0,79.0,0.0,debesuota
854139,Vilniaus AMS,vilniaus-ams,25.107064,54.625992,2026-03-01 23:00:00,1.7,-1.7,3.3,6.3,254.0,88.0,1021.8,81.0,0.0,debesuota

Aibės praleistos reikšmės

In [17]:
meteo_Vilnius.isnull().sum()

stoties_pavadinimas       0
stoties_kodas             0
ilguma                    0
platuma                   0
stebejimo_laikas          0
oro_temp                 27
juntamoji_temp           31
vejo_greitis             35
vejo_gusis               42
vejo_kryptis             32
debesuotumas           1509
slegis_juros_lyg         30
santyk_oro_dregme        35
kritutliu_kiekis         33
oro_salygos             334
dtype: int64