In [37]:
import pandas as pd
import os
import numpy as np
import pathlib

**PRIMINIMAS: Neleisti viso Note Book!**

### Neapjungtų metų sujungimas

In [40]:
path = "C:\\Users\\crist\\Downloads\\Processed_files_2023_2024\\"

csv_files = os.listdir(path = path)
csv_files[:6]

['gome2b_offline_2023_01_01.csv',
 'gome2b_offline_2023_01_02.csv',
 'gome2b_offline_2023_01_03.csv',
 'gome2b_offline_2023_01_04.csv',
 'gome2b_offline_2023_01_05.csv',
 'gome2b_offline_2023_01_06.csv']

In [41]:
def conect(name, path = path):
    return os.path.join(path, name)

df = pd.concat([
    pd.read_csv(conect(f)) for f in csv_files 
    if os.path.exists(conect(f)) and os.path.getsize(conect(f)) > 1
])

In [47]:
df.head()

,BrO,BrO_Error,H2O,H2O_Error,HCHO,HCHO_Error,NO2,NO2Tropo,NO2Tropo_Error,NO2_Error,O3,O3_Error,SO2,SO2_Error,lat,lon,date
0,3.693906e+13,6.694224e+12,-1.0,-1.0,-1.0,-1.0,1.076260e+15,-1.0,-1.0,1.057546e+14,343.81650,2.048706,-4.159356,4.128973,59.308010,18.382730,2023-01-01
1,3.999013e+13,6.554410e+12,-1.0,-1.0,-1.0,-1.0,1.123613e+15,-1.0,-1.0,1.105379e+14,347.85458,2.101421,-12.339394,15.620999,59.002254,18.007107,2023-01-01
2,2.787232e+13,6.391783e+12,-1.0,-1.0,-1.0,-1.0,1.194548e+15,-1.0,-1.0,1.018691e+14,336.82430,2.330087,-2.601628,2.601527,58.695423,17.638103,2023-01-01
3,3.314527e+13,6.370051e+12,-1.0,-1.0,-1.0,-1.0,1.123763e+15,-1.0,-1.0,1.028624e+14,338.16380,2.504560,-4.809435,235.171160,58.387550,17.275555,2023-01-01
4,3.874064e+13,6.601744e+12,-1.0,-1.0,-1.0,-1.0,1.249441e+15,-1.0,-1.0,9.818459e+13,337.98715,2.543163,-3.698821,12.234554,58.078716,16.919350,2023-01-01

In [48]:
downloads_dir_path = 'C:\\Users\\crist\\Downloads'

df.to_csv(os.path.join(downloads_dir_path, "GOME2B_DATA_2023_2024.csv"), index=False)

---
### Bendras sujungimas

In [43]:
csv_files = os.listdir(os.path.join(downloads_dir_path, 'ready GOME2'))
csv_files

['GOME2B_DATA_2022.csv',
 'GOME2B_DATA_2023_2024.csv',
 'GOME2B_DATA_2025.csv',
 'GOME2B_DATA_2026.csv']

In [49]:
final_df = pd.concat(pd.read_csv(os.path.join(downloads_dir_path, 'ready GOME2', f)) for f in csv_files)

In [50]:
final_df.shape

(1030435, 17)

In [51]:
final_df.replace(-1, np.nan)

,BrO,BrO_Error,H2O,H2O_Error,HCHO,HCHO_Error,NO2,NO2Tropo,NO2Tropo_Error,NO2_Error,O3,O3_Error,SO2,SO2_Error,lat,lon,date
0,6.138237e+13,1.579933e+13,6.256117,30.213684,NaN,NaN,1.633512e+15,NaN,NaN,1.950864e+14,389.16766,4.112923,-17.154598,31.190342,59.167020,30.981205,2022-01-01
1,4.364110e+13,1.518522e+13,6.970218,29.838783,NaN,NaN,1.195056e+15,NaN,NaN,2.048808e+14,387.23413,4.683897,26.328000,18.371586,59.287224,29.605570,2022-01-01
2,4.217024e+13,1.517903e+13,6.192209,33.005783,NaN,NaN,1.564458e+15,NaN,NaN,2.022072e+14,395.06537,5.054540,48.262356,28.617056,59.392982,28.222227,2022-01-01
3,2.786868e+13,1.478131e+13,6.528757,36.625190,NaN,NaN,1.219185e+15,NaN,NaN,1.814156e+14,382.86737,4.385046,-19.224960,60.634320,59.189410,29.814854,2022-01-01
4,2.471770e+13,1.562965e+13,NaN,NaN,NaN,NaN,1.409628e+15,NaN,NaN,1.939303e+14,405.50925,3.646466,-59.441666,41.271297,58.818924,30.852634,2022-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55780,5.155735e+13,1.438464e+13,NaN,NaN,NaN,NaN,1.595460e+15,1.801431e+15,1.970735e+15,1.675795e+14,428.50107,1.416726,-2.002236,8.607211,51.496574,19.091486,2026-02-08
55781,2.486765e+13,1.266010e+13,NaN,NaN,NaN,NaN,1.294561e+15,NaN,NaN,1.633897e+14,418.97104,1.726417,1.466866,2.582030,51.438680,16.580502,2026-02-08
55782,3.394596e+13,1.306851e+13,NaN,NaN,NaN,NaN,1.351132e+15,NaN,NaN,1.369905e+14,408.08258,1.836776,3.388359,3.552766,51.520470,15.440484,2026-02-08
55783,3.157099e+13,1.391171e+13,NaN,NaN,NaN,NaN,1.415115e+15,NaN,NaN,1.493191e+14,413.03372,2.058753,-18.999784,12.233781,51.590767,14.308120,2026-02-08
55784,4.226606e+13,1.431509e+13,NaN,NaN,NaN,NaN,1.516829e+15,1.579165e+15,2.307534e+15,1.440402e+14,423.22665,1.628642,3.094691,5.836656,51.480247,15.498205,2026-02-08